global using System.Linq.Expressions;
global using Data.Repository;
global using System.Data;
global using System.Data.SqlClient;
global using Business.Interface;
global using Data.Model;
global using Data.Repository.Interface;
global using Helper;
global using Microsoft.EntityFrameworkCore;