export const environment = {
  production: false, 
  DomainURL: "http://crm.giaongay.com.vn/",  
  DomainDestination: "http://crm.giaongay.com.vn/#/",  
  APIURL: "https://api.giaongay.com.vn/",    
  LoginURL: "http://login.giaongay.com.vn/",
  Website: "http://giaongay.com.vn/",
  Images: "images",  
  Download: "Download",  
  LoadingFile: "loading.gif",
  DialogConfigWidth: "80%",
  InitializationString: "",  
  InitializationNumber: 0, 
  CompanyIDThonTrang: 1, 
  CompanyIDBiBen: 2, 
  CompanyIDVyTam: 3, 
  AuthenticationToken: "AuthenticationToken",
  MembershipID: "MembershipID",  
  UploadSuccess: "Upload thành công.",
  UploadNotSuccess: "Upload không thành công.", 
  SaveSuccess: "Lưu thành công.",
  SaveNotSuccess: "Lưu không thành công.",  
  DeleteConfirm: "Bạn muốn xóa dữ liệu này?",      
  DeleteSuccess: "Xóa thành công.",
  DeleteNotSuccess: "Xóa không thành công.",    
  LoginNotSuccess: "Đăng nhập không thành công.",        
};

